[package]
name = "client"
edition = "2021"
version.workspace = true

[dependencies]
shared = { path = "../shared" }

# shared dependencies
anyhow = "1.0"
dashmap = "6.1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"

# client dependencies
network-interface = "2.0"
