[package]
name = "shared"
edition = "2021"
version.workspace = true

[dependencies]
opentelemetry = { version = "0.31", features = ["logs", "metrics", "trace"] }
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio", "logs", "metrics", "trace"] }
opentelemetry-otlp = { version = "0.31", features = ["grpc-tonic", "logs", "metrics", "trace"] }
opentelemetry-semantic-conventions = "0.31"
tracing = "0.1"
tracing-core = "0.1"
tracing-opentelemetry = "0.32"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
